version: '3'
services:
  jupyter_notebook:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./work:/home/jovyan/work
    ports:
      - 8888:8888
    command: "start-notebook.sh --NotebookApp.token="